name: Android Build

env:
  CI: true
  OPEN_API_KEY: ${{ secrets.SuperSecret }}

on:
  push:
      branches:
          - develop
  pull_request:
      branches:
          - develop

jobs:
  android_build:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: gradlew
      run: bash ./gradlew clean build test --stacktrace

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: apk_aar
        path: |
          **/*.apk
          **/*.aar
