name: iOS Build

env:
  CI: true
  OPEN_API_KEY: ${{ secrets.SuperSecret }}

on:
  push:
      branches:
          - develop
  pull_request:
      branches:
          - develop
      types:
          - opened
          - reopened
          - synchronize
          - ready_for_review

jobs:
  ios_tests:
    runs-on: macos-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: devbotsxyz/xcode-select@v1

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: xcodebuild
      run: xcodebuild -project "iosApp/iosApp.xcodeproj" -scheme iosApp test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' | tee xcodebuild.log | xcpretty && exit ${PIPESTATUS[0]}

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: results
        path: |
          /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
          xcodebuild.log
