name: iOS Build

on:
  push:
      branches:
          - develop
  pull_request:
      branches:
          - develop

env:
    CI: true

jobs:
  ios_tests:
    runs-on: macos-latest

    steps:
    - uses: devbotsxyz/xcode-select@v1

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: xcodebuild
      run: xcodebuild -project "iosApp/iosApp.xcodeproj" -scheme iosApp test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty && exit ${PIPESTATUS[0]}

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: tests.xcresult
        path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
